{
               
                "站名": "红果短剧",
                "请求头": "User-Agent@Mozilla/5.0 (Linux；； Android 9；； ASUS_I003DD Build/PI；； wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36&&Cookie@Hm_lvt_b7b8b64a02a5be0507f0c46011515b2b=1772677836；； HMACCOUNT=17BED804ED862610；； tackStats42615=1；； PHPSESSID=rhvlkmot07ad3e1bissc7gv154；； Hm_lpvt_b7b8b64a02a5be0507f0c46011515b2b=1772762863&&Accept@text/html,application/xhtml+xml,application/xml；；q=0.9,image/avif,image/webp,image/apng,*/*；；q=0.8,application/signed-exchange；；v=b3；；q=0.7&&Accept-Language@zh-CN,zh；；q=0.9",
                "编码": "UTF-8",
                "图片代理": "0",
                "直接播放": "0",
                "播放请求头": "",
                "嗅探词": ".mp4#.m3u8#.flv#hcts-m3u8#index.m3u8",
                "免嗅": "1",
                "过滤词": "",
                "主页url": "https://www.hgdj.app/",
                "首页": "120",
                "起始页": "1",
                "分类url": "https://www.hgdj.app/vodshow/{cateId}--------{catePg}---{year}.html",
                "分类": "短剧$duanju#电视剧$dianshiju#电影$dianying#动漫$dongman#",
                "二次截取": "",
                "数组": "hl-item-thumb hl-lazy&&</a>",
                "标题": "title=\"&&\"",
                "图片": "data-original=\"&&\"",
                "副标题": "<span class=\"hl-lc-1 remarks\">&&</span>",
                "链接": "href=\"&&\"",
                "影片年代": "年份：&&</li>",
                "影片地区": "地区：&&</li>",
                "影片类型": "类型：&&</li>",
                "状态": "状态：&&</li>",
                "导演": "导演：&&</li>",
                "主演": "主演：&&</li>",
                "简介": "简介：&&</div>",
                "线路二次截取": "",
                "线路数组": "href=\"\\#playlist&&</a>>[替换:线路1>>恒轩️]", 
                "线路标题": "data-toggle=\"tab\"&&</li>[不包含:线路2#线路3#线路4]",
                "播放二次截取": "",
                "播放数组": "<ul class=\"hl-plays-list hl-sort-list&&</ul>",
                "倒序": "0",
                "播放列表": "<a&&</a>",
                "播放标题": ">&&</a>",
                "播放链接": "href=\"&&\"",
                "解析": "",
                "跳转播放链接": "var player_*\"url\":\"&&\"",
                "跳转解析": "",
                "搜索请求头": "User-Agent$MOBILE_UA",
                "搜索url": "https://www.hgdj.app/vodsearch/{wd}----------{pg}---.html",
                "搜索模式": "1",
                "搜索后缀": "",
                "搜索二次截取": "",
                "搜索数组": "hl-item-thumb hl-lazy&&</a>",
                "搜索标题": "title=\"&&\"",
                "搜索图片": "data-original=\"&&\"",
                "搜索副标题": "<span class=\"hl-lc-1 remarks\">&&</span>",
                "搜索链接": "href=\"&&\""
            }